NOC = ['Management occupations',
       'Legislative and senior management occupations',
       'Specialized middle management occupations',
       'Middle management occupations in retail and wholesale trade and customer services',
       'Middle management occupations in trades, transportation, production and utilities',
       'Business, finance and administration occupations, except management',
       'Professional occupations in finance and business',
       'Professional occupations in finance',
       'Professional occupations in business',
       'Administrative and financial supervisors and specialized administrative occupations',
       'Administrative occupations and transportation logistics occupations',
       'Administrative and financial support and supply chain logistics occupations',
       'Natural and applied sciences and related occupations, except management',
       'Professional occupations in natural and applied sciences',
       'Professional occupations in natural sciences',
       'Professional occupations in applied sciences (except engineering)',
       'Professional occupations in engineering',
       'Technical occupations related to natural and applied sciences',
       'Health occupations, except management',
       'Professional occupations in health',
       'Health treating and consultation services professionals',
       'Therapy and assessment professionals',
       'Nursing and allied health professionals',
       'Technical occupations in health',
       'Assisting occupations in support of health services',
       'Occupations in education, law and social, community and government services, except management',
       'Professional occupations in law, education, social, community and government services',
       'Professional occupations in law',
       'Professional occupations in education services',
       'Professional occupations in social and community services',
       'Professional occupations in government services',
       'Front-line public protection services and paraprofessional occupations in legal, social, community, education services',
       'Occupations in front-line public protection services',
       'Paraprofessional occupations in legal, social, community and education services',
       'Assisting occupations in education and in legal and public protection',
       'Care providers and public protection support occupations and student monitors, crossing guards and related occupations',
       'Occupations in art, culture, recreation and sport, except management',
       'Professional occupations in art and culture',
       'Technical occupations in art, culture and sport',
       'Occupations in art, culture and sport',
       'Support occupations in art, culture and sport',
       'Sales and service occupations, except management',
       'Retail sales and service supervisors and specialized occupations in sales and services',
       'Occupations in sales and services',
       'Sales and service representatives and other customer and personal services occupations',
       'Sales and service support occupations',
       'Trades, transport and equipment operators and related occupations, except management',
       'Technical trades and transportation officers and controllers',
       'General trades',
       'Mail and message distribution, other transport equipment operators and related maintenance workers',
       'Helpers and labourers and other transport drivers, operators and labourers',
       'Natural resources, agriculture and related production occupations, except management',
       'Supervisors and occupations in natural resources, agriculture and related production',
       'Workers and labourers in natural resources, agriculture and related production',
       'Occupations in manufacturing and utilities, except management',
       'Supervisors, central control and process operators in processing, manufacturing and utilities and aircraft assemblers and inspectors',
       'Machine operators, assemblers and inspectors in processing, manufacturing and printing',
       'Labourers in processing, manufacturing and utilities']

GEO = ['Newfoundland and Labrador', 'Prince Edward Island',
       'Nova Scotia', 'New Brunswick', 'Quebec', 'Ontario', 'Manitoba',
       'Saskatchewan', 'Alberta', 'British Columbia', 'ALL']